name: CI

on:
  # Run the build for pushes and pull requests targeting main
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]

    steps:
      # Checkout doc repo and its dependencies
      - name: Checkout
        uses: actions/checkout@v2
      # Setup Node
      - name: Setup (Node.js ${{ matrix.node-version }})
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Install and build
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      # Run linkcheck, propagate linkcheck failure through grep pipe
      - name: Linkcheck
        run: set -o pipefail; yarn linkcheck 2>/dev/null | grep "Getting links from\|BROKEN"
        continue-on-error: false
